#Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 80
      targetPort: http-web-svc

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mercado-pago
data:
  MERCADO_PAGO_URL: "https://api.mercadopago.com/"
  URL_NOTIFICACAO: "https://www.yourserver.com/notifications"
---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
