services:
  app:
      container_name: lanchonete
      restart: always
      build: 
        dockerfile: Dockerfile
      ports:
        - '8080:8080'
      networks:
        - lanchonete-network
      depends_on:
        db:
          condition: service_healthy
      env_file:
      - .env

  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap
      MYSQL_DATABASE: lanchonete

    ports:
      - "3306:3306"
    expose:
      - "3306"

    restart: always
    volumes:
      - db:/var/lib/mysql

    networks:
      - lanchonete-network

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  db:
  rabbitmq:

networks:
  lanchonete-network:
    driver: bridge
