services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap
      MYSQL_DATABASE: lanchonete

    ports:
      - "3306:3306"

    restart: no
    volumes:
      - db:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10


volumes:
  db: